ZHSocialURL: http://10.144.182.142:8080/hygeia_esb_zh/api/call.action
function_id: sys0001
userid: SC000D
password: abc

his:
   userid: sa
   password: 146-164-156-
   ip: 127.0.0.1:51798
   database: his_yb
log:
   writers: file,stdout   
   logger_level: DEBUG
   logger_file: log/apiserver.txt
   log_format_text: true
   rollingPolicyj: size
   log_rotate_date: 1
   log_rotate_size: 2048
   log_backup_count: 7
 
zh:
   port: 6001
   userid: sa
   password: '146-164-156-'
   ip: 127.0.0.1
   sqlport: 51798
   database: gx_zh